name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Si no existe el wrapper, lo generamos (Gradle 8.7) y lo dejamos ejecutable
      - name: Ensure Gradle Wrapper
        shell: bash
        run: |
          if [ ! -f gradlew ]; then
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle --version
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x gradlew

      # (Opcional) Aceptar licencias si hiciera falta
      - name: Accept licenses
        shell: bash
        run: yes | sdkmanager --licenses || true

      - name: Build Debug APK
        shell: bash
        run: ./gradlew :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BTCPriceWidget-debug
          path: app/build/outputs/apk/debug/*.apk
